FROM java:8-jre-alpine
COPY target/universal/policy-enforcement-engine-1.0-SNAPSHOT.tgz app/policy-enforcement-engine-1.0-SNAPSHOT.tgz
EXPOSE 9000
RUN /bin/sh -c "apk add --no-cache bash"
RUN apk --update add tar
RUN ["apk", "add", "--update", "bash", "libc6-compat", "curl"]
RUN ["tar", "xvzf", "app/policy-enforcement-engine-1.0-SNAPSHOT.tgz", "-C", "app"]
ENTRYPOINT ["app/policy-enforcement-engine-1.0-SNAPSHOT/bin/policy-enforcement-engine",  "-Dplay.http.secret.key='wspl4r'", "-Dconfig.file=/app/policy-enforcement-engine-1.0-SNAPSHOT/conf/application.conf"]
