FROM java:8-jre-alpine
COPY target/universal/policy-enforcement-engine-1.0.tgz app/policy-enforcement-engine-1.0.tgz
EXPOSE 9000
RUN /bin/sh -c "apk add --no-cache bash"
RUN apk --update add tar
RUN ["apk", "add", "--update", "bash", "libc6-compat", "curl"]
RUN ["tar", "xvzf", "app/policy-enforcement-engine-1.0.tgz", "-C", "app"]
COPY test/resources/connections-DITAS-10000_pub.yml app/policy-enforcement-engine-1.0/conf/connections-DITAS.yml.sed
COPY test/resources/demo-dpcm-DITAS_pub.yml app/policy-enforcement-engine-1.0/conf/demo-dpcm-DITAS.yml.sed
COPY test/resources/PolicyEnforcement-application_pub.conf app/policy-enforcement-engine-1.0/conf/application.conf.sed
COPY ee-run.sh /app/policy-enforcement-engine-1.0/ee-run.sh
RUN chmod +x /app/policy-enforcement-engine-1.0/ee-run.sh
CMD ["/app/policy-enforcement-engine-1.0/ee-run.sh"]
